# minerx-usercenter 服务配置文件
http:
  addr: ${MINERX_USERCENTER_HTTP_ADDR} # HTTP 服务监听地址
grpc:
  addr: ${MINERX_USERCENTER_GRPC_ADDR} # gRPC 服务监听地址
tls:
  use-tls: ${MINERX_USERCENTER_TLS_USE_TLS} # 是否启用 TLS
  cert: ${MINERX_USERCENTER_TLS_CERT} # TLS 证书路径
  key: ${MINERX_USERCENTER_TLS_KEY} # TLS 私钥路径
mysql:
  host: ${MINERX_MYSQL_ADDR} # 数据库主机地址
  database: ${MINERX_MYSQL_DATABASE} # 数据库名称
  username: ${MINERX_MYSQL_USERNAME} # 数据库用户名
  password: ${MINERX_MYSQL_PASSWORD} # 数据库密码
  log-level: ${MINERX_MYSQL_LOG_LEVEL} # 数据库日志级别，1 为最低，4 为最高
redis:
  addr: ${MINERX_REDIS_ADDR} # Redis 地址
  database: ${MINERX_USERCENTER_REDIS_DATABASE} # Redis 数据库索引
  password: ${MINERX_REDIS_PASSWORD} # Redis 密码
etcd:
  endpoints: ${MINERX_ETCD_ENDPOINTS} # etcd 服务地址
kafka:
  brokers: ${MINERX_KAFKA_BROKERS}
  topic: ${MINERX_KAFKA_TOPIC}
  timeout: ${MINERX_KAFKA_TIMEOUT}
  # tls:
  #mechanism:
  #username:
  #password:
  #algorithm:
  #compressed:
  writer: # 使用默认值即可，不需要在 manifests/env.local 中配置
    max-attempts: 10
    required-acks: 1
    async: true
    batch-size: 100
    batch-timeout: 1s
    batch-bytes: 1024
jaeger:
  env: ${MINERX_JAEGER_ENV} # Jaeger 环境
  server: ${MINERX_JAEGER_ENDPOINT} # Jaeger 服务地址
  service-name: minerx-usercenter  # Jaeger 服务名称
log: # 使用默认值即可，不需要在 manifests/env.local 中配置
    level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
    enable-color: true # 是否开启颜色输出，true: 是，false: 否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再 panic 及以上级别禁止打印堆栈信息

